
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 30 20:53:42 CST 2020
//----------------------------------------------------

package Backend;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 3;
  public static final int error = 1;
  public static final int DIGITO = 2;
  public static final int EOF = 0;
}

